### PR TITLE
A new argument added, "--silent".

### PR DESCRIPTION
**Pull request by xaropizao**
This argument print only the results to the screen, to be used as a pipeline without interference of another things in output.
Exemple: `python3 paramspider.py -d hackerone.com --silent | qsreplace "'>"`

### CODE REVIEW

**Comment by devanshbatham** [comment]
There is "-quiet" which does the job tho, any reasons why the proposed changed is different?

**Comment by Miguel-Galdin0** [comment]
The quiet mode, don't print the result in screen, and the silent mode, ONLY show the results in screen, to be used in a pipeline.

**Comment by Miguel-Galdin0** [comment]
Look, i think this make clear what i'm doing.

NORMAL PARAMSPIDER, WITH QUIET MODE!
image

MY FORK PARAMSPIDER, WITH SILENT MODE!
image

**Comment by ruevaughn** [comment]
This is needed please.

**Comment by devanshbatham** [comment]
Closing this PR as I have revamped this whole project.

**Pull request closed without merging**
